extends "res://tests/world_objects.gd"

func interact(id: String, pos: Vector2i, choice: String = "accept") -> void:
	walk(pos,true)
	check(core.act({"op":"interact","target":id}).ok,"Start " + id)
	check(core.act({"op":"choose","choice":choice}).ok,"Choose " + id)

func _initialize() -> void:
	check(core.load_content("res://games/numeric_lab/game.json"),"Load P1 fixture")
	core.new_game()
	core.act({"op":"choose","choice":"accept"})
	var rule := {"kind":"action_count","tags":["work","train"],"op":"gte","value":2}
	check(not core.satisfied(core.content.events.milestone.conditions),"OR neither branch")
	for i in range(3): core.act({"op":"wait"})
	interact("work_desk",Vector2i(3,5))
	check(core.action_count(rule) == 1,"Multi-tag union counts once")
	interact("work_desk",Vector2i(3,5),"later")
	check(core.action_count(rule) == 1,"Cancellation does not count")
	interact("work_desk",Vector2i(3,5))
	check(core.satisfied(core.content.events.milestone.conditions),"Nested AND/count OR branch")
	var tree: Array = core.checks(core.content.events.milestone.conditions)
	check(tree[0].children[0].children.size() == 2,"Diagnostic tree keeps every child")
	check(core.save_game("user://p1.json") and core.load_game("user://p1.json") and core.action_count(rule) == 2,"Persistent action records")
	var before: Dictionary = core.state.duplicate(true)
	check(core.act({"op":"choose","choice":"accept"}).message == "no_event" and core.state == before,"No duplicate commit")
	walk(Vector2i(12,8),true)
	check(core.target_event_available(find("milestone_board")),"Available object marker")
	check(core.act({"op":"interact","target":"milestone_board"}).ok,"Nonlinear tracking does not gate entry")
	check(not core.act({"op":"choose","choice":"special"}).ok,"Live choice gameplay gate")
	core.act({"op":"choose","choice":"accept"})
	check(core.active_node == "reward","Branch node")
	core.act({"op":"choose","choice":"finish"})
	check(not core.target_event_available(find("milestone_board")),"Completed object hides marker")
	check(core.replay_session("milestone_replay",[]) == null,"Locked replay rejected")
	before = core.state.duplicate(true)
	check(core.save_game("user://p1.json"),"Save before replay")
	var disk := FileAccess.get_file_as_string("user://p1.json")
	var replay = core.replay_session("milestone_replay",["milestone_replay"])
	check(replay != null and replay.replay_mode,"Independent replay session")
	check(not replay.act({"op":"wait"}).ok and not replay.save_game("user://replay.json") and not replay.load_game("user://p1.json"),"Replay rejects world and persistence")
	check(replay.act({"op":"choose","choice":"special"}).ok,"Replay skips locked choice")
	check(replay.act({"op":"choose","choice":"finish"}).ok,"Replay completes full branch")
	check(replay.state == before and core.state == before and disk == FileAccess.get_file_as_string("user://p1.json"),"Replay has no state or file effects")
	walk(Vector2i(7,3),true)
	for i in range(3): check(core.act({"op":"buy","shop":"kiosk","item":"snack"}).ok,"Unlimited purchase")
	check(not core.state.stock.has("kiosk:snack") and core.state.inventory.snack == 3,"Unlimited has no fake stock")
	for i in range(2): check(core.act({"op":"buy","shop":"kiosk","item":"voucher"}).ok,"Finite daily stock purchase")
	check(core.act({"op":"buy","shop":"kiosk","item":"voucher"}).message == "out_of_stock","Finite exhausted")
	check(core.save_game("user://p1.json") and core.load_game("user://p1.json") and core.state.stock['kiosk:voucher'] == 0,"Load does not restock")
	core.act({"op":"wait"})
	check(core.state.day == 3 and core.state.stock['kiosk:voucher'] == 2,"Daily refill at crossing")
	before = core.state.duplicate(true)
	check(not core.apply_effects([{"kind":"money","value":10},{"kind":"stock","shop":"kiosk","id":"voucher","op":"add","value":1}]) and core.state == before,"Over-capacity restock rolls back whole transaction")
	check(core.apply_effects([{"kind":"stock","shop":"kiosk","id":"voucher","op":"set","value":0},{"kind":"stock","shop":"kiosk","id":"voucher","op":"add","value":1}]),"Explicit set/add restock")
	rule.window = {"unit":"days","size":1,"include_current":true}
	check(core.action_count(rule) == 0,"Current calendar day excludes yesterday")
	rule.window.include_current = false
	check(core.action_count(rule) == 2,"Explicit previous calendar day")
	rule.window = {"unit":"periods","size":1,"include_current":false}
	check(core.action_count(rule) == 0,"Previous period excludes older records")
	rule.window.size = 2
	check(core.action_count(rule) == 1,"Period window lower boundary inclusive")
	check(core.format_day(3,"en") == "Day 3" and core.format_day(4,"en") == "Extra Day 1","Shared extra-day formatter")
	core.content.date_display.normal_days = 90
	check(core.format_day(90,"en") == "Day 90" and core.format_day(91,"en") == "Extra Day 1" and core.format_day(92,"en") == "Extra Day 2","90-day policy boundaries")
	core.new_game()
	core.act({"op":"choose","choice":"accept"})
	for i in range(9): core.act({"op":"wait"})
	check(core.action_count(rule) == 0 and core.satisfied(core.content.events.milestone.conditions),"Independent date-only OR route through ordinary waiting")
	interact("milestone_board",Vector2i(12,8))
	core.act({"op":"choose","choice":"finish"})
	check("milestone" in core.state.completed and core.state.actions.is_empty(),"Date-only route completes with no training")
	check(core.save_game("user://extra.json") and core.load_game("user://extra.json") and core.state.day == 4,"Absolute day preserved in save")
	# Corrupted persistent actions fail closed, without replacing live state.
	var data = JSON.parse_string(FileAccess.get_file_as_string("user://extra.json"))
	data.state.actions = [{"event":"work","tags":["work"],"day":999,"period":"day"}]
	var file := FileAccess.open("user://corrupt.json",FileAccess.WRITE)
	file.store_string(JSON.stringify(data)); file.close()
	before = core.state.duplicate(true)
	check(not core.load_game("user://corrupt.json") and core.state == before,"Reject future action records")
	print(JSON.stringify({"p1_failures":failures}))
	quit(0 if failures.is_empty() else 1)
