extends "res://tests/world_objects.gd"

func _initialize() -> void:
	check(core.load_content(OS.get_cmdline_user_args()[0]), "Load fixture")
	walk(Vector2i(6,10), true)
	check(core.act({"op":"interact","target":"locker_key_pickup"}).ok, "Collect key")
	walk(Vector2i(10,10), true)
	check(core.act({"op":"interact","target":"harbor_locker","item":"locker_key"}).ok, "Open locker")
	walk(Vector2i(14,7), true)
	var ranking: Array = core.event_candidates("mara")
	var eligible: Array = ranking.filter(func(row): return row.eligible)
	check(eligible[0].id == "harbor_chat" and eligible[0].selected and eligible[1].reason == "lower_rank", "Stable ID tie-break diagnostics")
	check(core.act({"op":"interact","target":"mara_desk"}).event == "harbor_chat", "Selected side event")
	var before: Dictionary = core.state.duplicate(true)
	check(core.act({"op":"choose","choice":"work"}).message == "event_branch", "Enter work branch")
	check(core.state == before and core.active_node == "work" and core.pending_effects.size() == 1, "Branch effects deferred")
	check(core.act({"op":"interact","target":"mara_desk"}).message == "event_busy", "Cannot reenter active event")
	check(not core.save_game("user://branch.json"), "Mid-branch save refused")
	check(core.act({"op":"choose","choice":"work"}).message == "unknown_choice", "Previous node choice rejected")
	check(core.act({"op":"choose","choice":"locked"}).message == "choice_locked", "Locked branch choice rejected")
	check(core.act({"op":"choose","choice":"fail"}).message == "effect_failed", "Terminal effect failure")
	check(core.state == before and core.pending_effects.size() == 1 and core.active_node == "work", "Failed commit rolled back but allows retry")
	check(core.act({"op":"cancel_event"}).ok, "Mid-branch cancellation")
	check(core.state == before and core.pending_effects.is_empty() and core.active_node == "", "Cancel discards staged effects")
	check(core.act({"op":"interact","target":"mara_desk"}).ok, "Reenter cancelled event")
	check(core.act({"op":"choose","choice":"weather"}).ok, "Alternate branch")
	check(core.act({"op":"choose","choice":"accept"}).message == "event_completed", "Commit alternate branch")
	check(core.state.flags.chat_weather and not core.state.flags.get("chat_work", false), "Only chosen path applied")
	check(core.state.money == before.money + 2, "Event effect applied once")
	var committed: Dictionary = core.state.duplicate(true)
	check(core.act({"op":"choose","choice":"accept"}).message == "no_event" and core.state == committed, "Duplicate terminal callback cannot pay twice")
	check(core.act({"op":"interact","target":"mara_desk"}).ok, "Repeat side event")
	check(core.act({"op":"choose","choice":"work"}).ok, "Repeat chooses another branch")
	check(core.act({"op":"choose","choice":"accept"}).ok, "Repeat terminal")
	check(core.state.flags.chat_work and core.state.money == before.money + 4, "Repeat effects once per complete run")
	check(core.state.completed.count("harbor_chat") == 1, "Completed ID remains unique")
	check(core.save_game("user://branch.json") and core.load_game("user://branch.json"), "Save/load completed repeatable event")
	check(core.act({"op":"interact","target":"mara_desk"}).event == "harbor_chat", "Repeat eligibility survives load")
	check(core.act({"op":"choose","choice":"later"}).ok and core.pending_effects.is_empty(), "Authored cancellation clears session")
	walk(Vector2i(11,10), true)
	check(core.act({"op":"interact","target":"harbor_note"}).ok, "Unlock high priority fixture")
	walk(Vector2i(14,7), true)
	check(core.act({"op":"interact","target":"mara_desk"}).event == "z_priority", "Numeric priority wins over ID")
	check(core.act({"op":"choose","choice":"accept"}).ok, "Complete one-shot priority event")
	ranking = core.event_candidates("mara")
	check(ranking[0].id == "z_priority" and ranking[0].reason == "completed" and not ranking[0].eligible, "One-shot exclusion diagnostic")
	check(core.act({"op":"interact","target":"mara_desk"}).event == "harbor_chat", "Completed priority no longer shadows repeatable")
	check(core.act({"op":"choose","choice":"work"}).ok, "Prepare interrupted run")
	core.new_game()
	check(core.active_event == "" and core.active_node == "" and core.pending_effects.is_empty(), "New game clears interrupted session")
	print(JSON.stringify({"story_contract_failures": failures}))
	quit(0 if failures.is_empty() else 1)
